CREATE TABLE IF NOT EXISTS `dx_stu_login` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `user_name` CHAR(15) DEFAULT NULL COMMENT '登录账号，默认为学号',
  `user_pwd` CHAR(15) DEFAULT NULL COMMENT '登录密码，默认为学号',
  `name` VARCHAR(25) DEFAULT NULL COMMENT '学员名字',
  `belong` TEXT COMMENT '所属单位或班级',
  `specialty` TEXT COMMENT '专业方向',
  `start_time` DATE DEFAULT NULL COMMENT '列为发展对象的时间',
  `pass_rate` TEXT COMMENT '推优通过率',
  `class` INT(11) DEFAULT NULL COMMENT '所属班别',
  `group` INT(11) DEFAULT NULL COMMENT '班内分组',
  `Tel` TEXT COMMENT '只要求正副组长要求填写，格式为正+电话号码，副组长方式类似',
  `header_status` INT(11) DEFAULT '0' COMMENT '0为一般组员；1为正组长；2为副组长；',
  `status` INT(11) DEFAULT '0' COMMENT '0表示未审核，1表示第一次登录，大于1表示登录次数',
  `school_zone` VARCHAR(30) DEFAULT '广东医学院（东莞校区）' COMMENT '校区',
  `period` INT(11) DEFAULT NULL COMMENT '培训期数',
  `study_class_no` VARCHAR(20) DEFAULT NULL COMMENT '上课教室号',
  `study_seat` INT(11) DEFAULT NULL COMMENT '上课座位号',
  `test_class_no` VARCHAR(20) DEFAULT NULL COMMENT '考试教室号',
  `test_seat` INT(11) DEFAULT NULL COMMENT '考试座位号',
  `score` FLOAT DEFAULT NULL COMMENT '总评成绩',
  `certificate_number` INT(11) DEFAULT NULL COMMENT '结业证书号',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=MYISAM DEFAULT CHARSET=gbk COMMENT='学生端登录表' AUTO_INCREMENT=1 ;